#     _    _                 _ _   _         
#    / \  | | __ _  ___ _ __(_) |_| |_ _   _ 
#   / _ \ | |/ _` |/ __| '__| | __| __| | | |
#  / ___ \| | (_| | (__| |  | | |_| |_| |_| |
# /_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                      |___/ 

# Author: sunaneko
# ----------------
# Alacritty settings root init file.
# Other settings file is imported by here.


# Import other files
import = [
  "~/.config/alacritty/window.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/themes/nord.toml"
]
