#   __             _   
#  / _| ___  _ __ | |_ 
# | |_ / _ \| '_ \| __|
# |  _| (_) | | | | |_ 
# |_|  \___/|_| |_|\__|
#                      

# Author: sunaneko
# ----------------
# Font related settings is here.

[font]
normal = { family = "HackGen35 Console NF", style = "Regular" }
size = 16

