#           _           _               
# __      _(_)_ __   __| | _____      __
# \ \ /\ / / | '_ \ / _` |/ _ \ \ /\ / /
#  \ V  V /| | | | | (_| | (_) \ V  V / 
#   \_/\_/ |_|_| |_|\__,_|\___/ \_/\_/  
#                                       

# Author: sunaneko
# ----------------
# Window related settings is here.

[window]
decorations = "buttonless"
opacity = 1

startup_mode = "Maximized"

title = ""
